### ISSUE TITLE
Returning multiple values from C#

### ISSUE THREAD

**Issue by theconezone** [NLua/NLua#215]
Is it possible to return multiple values from C# to Lua?

IE:

```
local a, b = someClass:someCSharpFunction()
```

This doesn't work.

```
public SomeClass {
    private Lua state;
    public SomeClass(Lua state) {
        this.state = state;
    }
    public void someCSharpFunction() {
        state.Push("a");
        state.Push("b");
    }
}
```

Returning an array doesn't work, as a will be System.Object[] and b will be nil. The same for returning a collection.

I could potentially register a C# function as a LuaNativeFunction, but that seems incredibly dirty compared to how clean the rest of NLua is.

**Comment by tdenniston** [comment]
By reading some of the original LuaInterface documentation (NLua is based on LuaInterface), I learned this is possible by using C# 'out' parameters. From section 2.4 in http://underpop.free.fr/l/lua/docs/luainterface.pdf:

> Lua offers only call-by-value parameters, so LuaInterface supports out and ref parameters using multiple return values (functions in Lua can return any number of values).  LuaInterface returns the values of out and ref parameters after the method's return value, in the order they appear in the method's signature. The method call should omit out parameters.

As an example, suppose you write a normal C# function returning a `Tuple<string, int, float>` type, i.e. a function with 3 return values. In order to return 3 values to Lua, you'd have to write the C# method like this:

```
public string foo(out int x, out float y) {
    x = 10;
    y = 13.6f;
    return "hello";
}
```

And call from Lua like this:

```
s, a, b = foo();
print(s, a, b);        -- Prints "hello  10  13.60000038147"
```

Hope this helps!

**Comment by JCH2k** [comment]
Are there plans to support the new C#7 tuples (System.ValueTuple return type)?
This way it would be possible to write C# functions with many return values just like in lua!
It would make API syntax a lot more readable...

```
[LuaFunction("DoSomething")
public (int, int) DoSomething(int a, int b)
{
  int multi = a*b;
  int sum = a+b;
  return (multi, sum);
}
```

**Comment by viniciusjarina** [comment]
Not right now, in theory would be possible if we can read the tuples information using reflection.
