### ISSUE TITLE
Request - Bump version to Lua 5.3.4 

### ISSUE THREAD

**Issue by RevoluPowered** [NLua/NLua#252]
Curious if it would be possible to bump the supported version up to the latest?

**Comment by Artum** [comment]
I've tried... Don't have enough time to make it happens.

The problem is that NLua (or more precisely KeraLua) is using modified LUA sources.
The main changes are: 

- Code was compiled as C++ (including build chain changes).

- There is additional functionality added on top of the "standard" LUA code, some functions like 'luanet_pushwstring' function and others.

**Comment by RevoluPowered** [comment]
I've got this working with the latest:
"Code was compiled as C++ (including build chain changes)."

could you point me at the source code for the changes you made to Lua? I'll see if I get time to port it over for you.

**Comment by Artum** [comment]
Good news. 
I have finally bumped the version to 5.3.4.
It is on my fork: https://github.com/Artum/NLua (branch: lua-5.3.4).

**Comment by RevoluPowered** [comment]
Thank you @Artum, that's great news!

**Comment by AndySingularity** [comment]
Hello, @Artum.
Is there any success in this direction? It would be great to see NLua working on 5.3.4 since in Lua5.3 there is 
**basic UTF-8 support** and there won't be such problems as [for example this one.](https://github.com/NLua/NLua/pull/223)
Also what about the DLL? I didn't find working one (I tried [these options](https://sourceforge.net/projects/luabinaries/files/5.3.4/Windows%20Libraries/Dynamic/))

**Comment by Kurruk007** [comment]
You can get the DLL by ensuring all submodules were downloaded and building them.

The binary is stored at:
`.\Core\KeraLua\external\lua\build\win64_rel\bin64\lua53.dll`

**Comment by Artum** [comment]
Hi guys, please feel free to use the branch and try to merge it back (actually it will awesome). I currently don't have plan and time to do it. Sorry.

**Comment by vadosnaprimer** [comment]
So did anything happen on this front? Can't find in the commits.

**Comment by Kurruk007** [comment]
Hey @vadosnaprimer, sorry but I haven't got any time to try and wrap it up.

Considering at work I was working on VS2013 as my latest version, I discovered that some of the features weren't available and AFAIR had to revert at least the default value of property to be setup in constructor instead (introduced in VS2017? C#6 and higher). Additionally I upped the dotnet version to (I believe) 4.7.2. This allowed me to do some cross-compilation on the Gitlab's linux CI under dotnetcore. Should have some of the patches lying somewhere, but wanted to ensure that everything is kind of consistent with the rest of the project (hacked it myself for the project I was working on) before introducing PR.

It's on my TODO list, so hopefully will happen at some stage.
