### ISSUE TITLE
Static methods are unusable unless they come from import()

### ISSUE THREAD

**Issue by JTinkers** [NLua/NLua#318]
Greetings,
There's an issue when using static methods of classes exposed via `LuaState[name] = class` approach.

**Here's what I've tried so far:**
**First attempt:**
I've created a static class with a static void method called Print()

I've registered it this way:
`State["StaticMethodClass"] = typeof(StaticMethodClass);`

Then I've ran:
`StaticMethodClass.Print()`

The result: `[string "chunk"]:1: attempt to call a string value (field 'Print')`

**Second attempt:**
I've created a non-static class with a static void method called Print()

I've registered it this way:
`State["StaticMethodClassInstanced"] = new StaticMethodClassInstanced();`

Then I've ran:
`StaticMethodClassInstanced.Print()`

The result: `Can't pass instance to static method Print`

It's worth mentioning - in both cases I've tried replacing `.` with `:` to no avail and that running:
`import("System")
Console.WriteLine("Test")`

**Works flawlessly.**

**Comment by viniciusjarina** [comment]
Hello @JTinkers thank you for the issue report. I know NLua doesn't have a lot of documentation. But this is not how NLua works, you can't call from the Type because NLua uses reflection to find the Method, trying to call a method Print from the Type would be similar to try `typeof(StaticMethodClass).Print` which is invalid. Also you can't call from an object, the same way you can call from a reference in C#.

There a couple of ways to do what you want. You choose whatever you think is better for you

* Use [`RegisterFunction`](https://github.com/NLua/NLua/blob/master/tests/src/LuaTests.cs#L243) and register a Lua method to call your static C# method.
* Use [`luanet.import_type`](https://github.com/NLua/NLua/blob/master/tests/src/LuaTests.cs#L283) to import only the type where is your static library.
* Create a delegate and use it from the Lua code: 
```csharp
                lua.DoString("FakeType = {}");
                lua["FakeType.bar"] = (Func<object[],int>) TestClass.MethodWithObjectParams;
                lua.DoString("i = FakeType.bar('one', 1)");
```

You can wrap your delegate inside a Lua table to pretend is inside a "Type"
