### ISSUE TITLE
Where can I find the compiled 5.2 lua dll?

### ISSUE THREAD

**Issue by dfinke** [NLua/NLua#38]
Sorry for the newb question. Maybe I haven't dug deep enough.

Thanks

**Comment by stenya** [comment]
Hello!

I downloaded lua52.dll from this link:
   Win32: **Download** [![dwn_w32][8]][7]
         [7]: https://www.dropbox.com/s/jkr1pnwvqw6w0r8/NLua.Win32.zip

But, current version of lua52.dll is compiled with VS2013 (requires MSVCR120.dll and MSVCP120.dll).
I want to have it compiled with VS2010.

Where I can get an sources of lua52.dll in order to recompile it myself?
Thanks.
