### ISSUE TITLE
To run Lua CLRPackage

### ISSUE THREAD

**Issue by shim-t-tamura** [NLua/NLua#395]
Hello, could you kindly teach me one thing?

I ran a sample in extras\examples.

I could successfully run a sample with NLua.exe, but when I ran it with lua.exe after writing NLua.dll and other files that is included in lib\Release folder in package.cpath, I got error like this:

module 'luanet' not found. 

How can I solve this problem?

Thank you in advance.

**Comment by viniciusjarina** [comment]
Hi @shim-t-tamura 
I am not sure what you are trying to do. In any case NLua is library to be loaded from a C# application. NLua.exe is just a example on how you would use to load scripts integrating with your C# applications.

Ideally you may want to write your "bootstrap"  aplication in C# using NLua and just load and run your Lua scripts.

**Comment by shim-t-tamura** [comment]
＠viniciusjarina
Thank you for your response.

I'm trying to use .NET libraries from a lua script.
Could you see the attached files?
In 'test.lua', I'm trying to create a instance of a class of a .NET library.
I thought that CLRPackage bounds .NET and Lua, but it doesn't work.
Could you kindly teach me how I can solve this?

[NLuaTest.zip](https://github.com/NLua/NLua/files/5362475/NLuaTest.zip)

**Comment by viniciusjarina** [comment]
Hi @shim-t-tamura 
NLua is a .NET library, all you have to do is add NLua to your C# project and use the APIs to load your Lua scripts

There are several projects using NLua, you can try how they do it https://github.com/NLua/NLua/network/dependents

Or you can see how our tests work https://github.com/NLua/NLua/blob/447e7d2b88f058bc2b292db0fdda4cd12c48c72e/tests/src/LuaTests.cs#L2435

You won't be able to Load CLR from the original lua.exe since isn't a .NET application

Thanks

**Comment by shim-t-tamura** [comment]
@viniciusjarina 

Thank you for your quick response.
>You won't be able to Load CLR from the original lua.exe since isn't a .NET application
 I understand. Thank you.
