### ISSUE TITLE
NLua and Xamarin Forms

### ISSUE THREAD

**Issue by davepruitt** [NLua/NLua#412]
According to the NLua website, it is "compatible with Xamarin.iOS/Mac/Android/.NET/.NET Core". In the Nuget package manager, it says that NLua allows use of Lua in C# using "Windows, UWP, Linux, Android, Mac, iOS, tvOS".

Based on that information, I would assume it would be okay to use NLua in a "Xamarin Forms" project, and I would also assume that NLua is built on .NET Standard.

However, when I include NLua in my "Xamarin Forms" project, I get the following warning:

```
Warning: Package 'NLua 1.5.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2,
.NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8'
instead of the project target framework '.NETStandard,Version=v2.0'. 
This package may not be fully compatible with your project. 
```

When I run my Xamarin Forms project, NLua *seems to work*, but this is just in a very limited debugging situation. I am only running the following code:

```
NLua.Lua state = new NLua.Lua();
var res = state.DoString("return 10 + 3*(5 + 2)")[0];
```

So I just wanted to clarify: does NLua work properly within Xamarin Forms? Why am I receiving the above warning? Should I expect it to crash and burn, especially outside of a debugging situation?

Thank you!

**Comment by viniciusjarina** [comment]
It works, in the end of the day X.F is just another .NET library. Your final binary will be targeting an actual .NET target (like .NET 4.7 or Xamarin.iOS or Xamarin.Android)

I have dropped the .NET Standard from the NuGet on 1.5.7

There is a couple of reasons for that:
- I have added .NET 5
- Also  you could end up trying to load the wrong version of KeraLua since it does DLLImport("lua54") but that might fail on iOS.

So you can reference 1.5.6 if you really need .NET Standard,but in the end executable the actual target should be used.

Personally for Forms I prefer to use shared asset project instead .NET Standard.

**Comment by davepruitt** [comment]
Cool, thank you!
